#!/bin/sh

# ensure ~/.fonts exists
if [ ! -d ~/.fonts ]; then
    mkdir ~/.fonts
fi

cp -t ~/.fonts {*.bdf,*.otb}

# install the fonts
mkfontdir ~/.fonts
mkfontscale ~/.fonts
xset +fp ~/.fonts
xset fp rehash
fc-cache
fc-cache -fv
