#!/bin/sh

# create the pcf files
for file in *.bdf; do
    bdftopcf -o "~/.fonts/${file%\.*}.pcf" "$file"
done

# install the fonts
mkfontdir ~/.fonts
mkfontscale ~/.fonts
xset +fp ~/.fonts
xset fp rehash
fc-cache
fc-cache -fv
